### ISSUE TITLE
Dropdown cart not 'removing' dropdown menu

### ISSUE THREAD

**Issue by woutr-nl** [Widdin/wp_oxygen#2]
Hey!

I've added the shortcode, and the dropdown menu is not going away; https://gordijnhuis.woutr.io/

How can i fix this? Any idea?

**Comment by Widdin** [comment]
Updated the tutorial, [drop-down-cart](https://github.com/Widdin/wp_oxygen/blob/master/woocommerce/drop-down-cart.md)
